# Exploratory Data Analysis

### Structure Overview

In [ ]:
# Set up libraries and data
import pandas as pd

train_df = pd.read_csv('../data/train.csv')
test_df = pd.read_csv('../data/test.csv')

In [20]:
train_df.head()

,patient_id,age,gender,blood_pressure_systolic,blood_pressure_diastolic,heart_rate,respiratory_rate,body_temperature,oxygen_saturation,glucose_fasting,cholesterol_total,pain_score,diabetes,smoker,readmitted_30_days
0,P102308,20,Male,161,114,100,29,97.4,95,124,246,1,1,0,0
1,P122404,24,Female,159,89,76,21,96.7,95,172,292,1,0,0,0
2,P123397,77,Female,104,68,97,18,99.9,86,165,234,3,0,0,1
3,P125058,45,Male,143,102,72,26,98.5,87,106,166,2,1,0,0
4,P102664,50,Female,115,91,53,15,98.5,90,135,224,4,0,0,0

In [21]:
test_df.head()

,patient_id,age,gender,blood_pressure_systolic,blood_pressure_diastolic,heart_rate,respiratory_rate,body_temperature,oxygen_saturation,glucose_fasting,cholesterol_total,pain_score,diabetes,smoker
0,P102308,20,Male,161,114,100,29,97.4,95,124,246,1,1,0
1,P122404,24,Female,159,89,76,21,96.7,95,172,292,1,0,0
2,P123397,77,Female,104,68,97,18,99.9,86,165,234,3,0,0
3,P125058,45,Male,143,102,72,26,98.5,87,106,166,2,1,0
4,P102664,50,Female,115,91,53,15,98.5,90,135,224,4,0,0

In [22]:
train_df.shape

(30000, 15)

In [ ]:
test_df.shape

(6000, 14)

In [ ]:
train_df.columns

Index(['patient_id', 'age', 'gender', 'blood_pressure_systolic',
       'blood_pressure_diastolic', 'heart_rate', 'respiratory_rate',
       'body_temperature', 'oxygen_saturation', 'glucose_fasting',
       'cholesterol_total', 'pain_score', 'diabetes', 'smoker',
       'readmitted_30_days'],
      dtype='str')

In [ ]:
test_df.columns

Index(['patient_id', 'age', 'gender', 'blood_pressure_systolic',
       'blood_pressure_diastolic', 'heart_rate', 'respiratory_rate',
       'body_temperature', 'oxygen_saturation', 'glucose_fasting',
       'cholesterol_total', 'pain_score', 'diabetes', 'smoker'],
      dtype='str')

In [32]:
train_only = set(train_df.columns) - set(test_df.columns)
train_only

{'readmitted_30_days'}

In [34]:
test_only = set(test_df.columns) - set(train_df.columns)
test_only

set()

In [26]:
train_df.dtypes

patient_id                      str
age                           int64
gender                          str
blood_pressure_systolic       int64
blood_pressure_diastolic      int64
heart_rate                    int64
respiratory_rate              int64
body_temperature            float64
oxygen_saturation             int64
glucose_fasting               int64
cholesterol_total             int64
pain_score                    int64
diabetes                      int64
smoker                        int64
readmitted_30_days            int64
dtype: object

In [27]:
test_df.dtypes

patient_id                      str
age                           int64
gender                          str
blood_pressure_systolic       int64
blood_pressure_diastolic      int64
heart_rate                    int64
respiratory_rate              int64
body_temperature            float64
oxygen_saturation             int64
glucose_fasting               int64
cholesterol_total             int64
pain_score                    int64
diabetes                      int64
smoker                        int64
dtype: object

## Structural Overview - Findings
- train: rows and columns match EHRs structure and shape
- test: same columns as train without target/readmission column
- dtypes are expected
- no stray columns